CREATE SCHEMA UNI2;
USE UNI2;

CREATE TABLE Docentes(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL);

CREATE TABLE Horarios(
id INT AUTO_INCREMENT PRIMARY KEY,
hora_inicial TIME NOT NULL,
hora_final TIME NOT NULL);

CREATE TABLE Aulas(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL);

CREATE TABLE Estudiantes(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(30)NOT NULL);

CREATE TABLE Cursos(
id INT AUTO_INCREMENT PRIMARY KEY ,
nombre VARCHAR(30) NOT NULL,
id_docente INT NOT NULL,
FOREIGN KEY (id_docente) REFERENCES Docentes(id),
id_horario INT NOT NULL,
FOREIGN KEY (id_horario) REFERENCES Horarios(id));

CREATE TABLE Curso_aula(
id INT AUTO_INCREMENT PRIMARY KEY,
id_aula INT NOT NULL,
FOREIGN KEY (id_aula) REFERENCES Aulas(id),
id_curso INT NOT NULL,
FOREIGN KEY (id_curso) REFERENCES Cursos(id));

CREATE TABLE Clase(
id INT AUTO_INCREMENT PRIMARY KEY,
id_estudiante INT NOT NULL,
FOREIGN KEY (id_estudiante) REFERENCES Estudiantes(id),
id_curso_aula INT NOT NULL,
FOREIGN KEY (id_curso_aula) REFERENCES Curso_aula(id));